// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO1SSd4oG9WldJ4rvz0YoMLl5ub0qoSm4',
    appId: '1:457525028134:web:603731911b7088b4ee4de7',
    messagingSenderId: '457525028134',
    projectId: 'sac-iit-pkd',
    authDomain: 'sac-iit-pkd.firebaseapp.com',
    storageBucket: 'sac-iit-pkd.firebasestorage.app',
    measurementId: 'G-BKL5VNZBPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHQRvhCCpISSbNEGpS3HRmf6FQ80EJQLg',
    appId: '1:457525028134:android:a530ac9a6da33747ee4de7',
    messagingSenderId: '457525028134',
    projectId: 'sac-iit-pkd',
    storageBucket: 'sac-iit-pkd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvARN294vkeJuJG_sdtBwAxhSlPlKUE4I',
    appId: '1:457525028134:ios:7a5f40c2bb122fc9ee4de7',
    messagingSenderId: '457525028134',
    projectId: 'sac-iit-pkd',
    storageBucket: 'sac-iit-pkd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvARN294vkeJuJG_sdtBwAxhSlPlKUE4I',
    appId: '1:457525028134:ios:7a5f40c2bb122fc9ee4de7',
    messagingSenderId: '457525028134',
    projectId: 'sac-iit-pkd',
    storageBucket: 'sac-iit-pkd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO1SSd4oG9WldJ4rvz0YoMLl5ub0qoSm4',
    appId: '1:457525028134:web:da5675ff784e3132ee4de7',
    messagingSenderId: '457525028134',
    projectId: 'sac-iit-pkd',
    authDomain: 'sac-iit-pkd.firebaseapp.com',
    storageBucket: 'sac-iit-pkd.firebasestorage.app',
    measurementId: 'G-K23D60WRT6',
  );
}
